# Generated by Django 5.2.8 on 2025-12-02 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_team_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(help_text='Team lead responsible for this team', on_delete=django.db.models.deletion.CASCADE, related_name='teams_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
