# Generated by Django 5.2.8 on 2025-12-15 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_status'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='Optional link to a specific project task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.task'),
        ),
    ]
