# Generated by Django 5.2.8 on 2025-12-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timeentry_related_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='related_task',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
