# Generated by Django 5.2.8 on 2025-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('frontend_dev', 'Frontend Developer'), ('backend_dev', 'Backend Developer'), ('fullstack_dev', 'Full Stack Developer'), ('mobile_dev', 'Mobile Developer'), ('ui_ux_designer', 'UI/UX Designer'), ('project_manager', 'Project Manager'), ('hr', 'HR'), ('qa', 'Quality Assurance'), ('devops', 'DevOps Engineer')], max_length=50, null=True),
        ),
    ]
