# Generated by Django 5.2.8 on 2025-12-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
    ]
