# Generated by Django 5.2.8 on 2025-12-09 12:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField(help_text='Work day start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Work day end time', null=True)),
                ('total_break_time', models.DurationField(default=datetime.timedelta(0), help_text='Total duration of all breaks')),
                ('total_work_time', models.DurationField(blank=True, help_text='Total work time (end_time - start_time - total_break_time)', null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-start_time'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.DateTimeField(help_text='Break start time')),
                ('break_end', models.DateTimeField(blank=True, help_text='Break end time (null if break is still running)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(help_text='The attendance record this break belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendance')),
            ],
            options={
                'verbose_name': 'Attendance Break',
                'verbose_name_plural': 'Attendance Breaks',
                'ordering': ['break_start'],
            },
        ),
    ]
